### ISSUE TITLE
Return proper response when Avro lacks __metadata

### ISSUE THREAD

**Issue by adamdubiel** [allegro/hermes#1058]
When publishing on Avro topic, which has no `__metadata` field declared in schema, you get `500` with:

```
{
    "code": "INTERNAL_ERROR",
    "message": "Exception caught while creating message"
}
```

and exception is logged:

```
Exception caught while creating message; publishing on topic: XXX; message id: 20ae09bc-5578-4bbf-b061-d9254d123d7f; remote host: XXXXX

pl.allegro.tech.hermes.common.message.wrapper.WrappingException: Could not wrap avro message
	at pl.allegro.tech.hermes.common.message.wrapper.AvroMessageContentWrapper.wrapContent(AvroMessageContentWrapper.java:68)
	at pl.allegro.tech.hermes.common.message.wrapper.MessageContentWrapper.wrapAvro(MessageContentWrapper.java:123)
	at pl.allegro.tech.hermes.frontend.publishing.message.MessageFactory.createAvroMessage(MessageFactory.java:110)
	at pl.allegro.tech.hermes.frontend.publishing.message.MessageFactory.create(MessageFactory.java:86)
	at pl.allegro.tech.hermes.frontend.publishing.message.MessageFactory.create(MessageFactory.java:60)
	at pl.allegro.tech.hermes.frontend.publishing.handlers.MessageCreateHandler.handleRequest(MessageCreateHandler.java:35)
	at pl.allegro.tech.hermes.frontend.publishing.handlers.PreviewHandler.handleRequest(PreviewHandler.java:22)
	at pl.allegro.tech.hermes.frontend.publishing.handlers.MessageReadHandler.finalizeMessageRead(MessageReadHandler.java:169)
	at pl.allegro.tech.hermes.frontend.publishing.handlers.MessageReadHandler.messageRead(MessageReadHandler.java:147)
	at pl.allegro.tech.hermes.frontend.publishing.handlers.MessageReadHandler.lambda$partialMessageRead$2(MessageReadHandler.java:115)
	at io.undertow.io.AsyncReceiverImpl.receivePartialBytes(AsyncReceiverImpl.java:582)
	at pl.allegro.tech.hermes.frontend.publishing.handlers.MessageReadHandler.readMessage(MessageReadHandler.java:90)
	at pl.allegro.tech.hermes.frontend.publishing.handlers.MessageReadHandler.handleRequest(MessageReadHandler.java:61)
	at pl.allegro.tech.hermes.frontend.publishing.handlers.TopicHandler.lambda$handleRequest$0(TopicHandler.java:51)
	at pl.allegro.tech.hermes.frontend.publishing.handlers.TopicHandler.onRequestValid(TopicHandler.java:79)
	at pl.allegro.tech.hermes.frontend.publishing.handlers.TopicHandler.handleRequest(TopicHandler.java:47)
	at io.undertow.server.handlers.SetHeaderHandler.handleRequest(SetHeaderHandler.java:90)
	at io.undertow.security.handlers.AuthenticationCallHandler.handleRequest(AuthenticationCallHandler.java:52)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:332)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.avro.AvroRuntimeException: Not a valid schema field: __metadata
	at org.apache.avro.generic.GenericData$Record.put(GenericData.java:201)
	at pl.allegro.tech.hermes.common.message.wrapper.AvroMessageContentWrapper.wrapContent(AvroMessageContentWrapper.java:65)
	... 22 common frames omitted
```

We should return 400 with proper message instead.

**Comment by druminski** [comment]
Hint: we have integration tests with publishing on topic with avro type.
