### ISSUE TITLE
SchemaNotFoundException returns 5xx

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#1241]
When a client publishes on Hermes a message with `Schema-version` header which doesn’t  exist in `schema-registry` then Hermes returns 5xx to the client. Hermes also logs something like this:

```
pl.allegro.tech.hermes.schema.SchemaNotFoundException: No schema source for topic X.X.X at version Y
	at pl.allegro.tech.hermes.schema.SchemaRepository.getAvroSchema(SchemaRepository.java:30)
	at pl.allegro.tech.hermes.frontend.publishing.message.MessageFactory.lambda$createAvroMessage$0(MessageFactory.java:104)
	at java.base/java.util.Optional.map(Optional.java:265)
	at pl.allegro.tech.hermes.frontend.publishing.message.MessageFactory.createAvroMessage(MessageFactory.java:104)
	at pl.allegro.tech.hermes.frontend.publishing.message.MessageFactory.create(MessageFactory.java:89)
	at pl.allegro.tech.hermes.frontend.publishing.message.MessageFactory.create(MessageFactory.java:63)
	at pl.allegro.tech.hermes.frontend.publishing.handlers.MessageCreateHandler.handleRequest(MessageCreateHandler.java:38)
```

When some schema version doesn’t really exists in `schema-registry` then Hermes should return 4xx instead of 5xx to a client which send non existing schema version.

**Comment by jewertow** [comment]
```
public CompiledSchema<Schema> getAvroSchema(Topic topic, SchemaVersion version) {
    if (!schemaVersionsRepository.schemaVersionExists(topic, version)) {
        throw new SchemaNotFoundException(topic, version);
    }
    return getCompiledSchemaAtVersion(topic, version);
}
```
The implementation of `schemaVersionExists` uses `SchemaVersionsRepository.versions` which fetches all versions from schema-registry and returns versions or in case of failure returns an empty list of versions. 
Instead of returning an empty list we should catch thrown exception, wrap in a dedicated one, propagate it and handle on the calling side. Then it will be possible to return 400 Bad Request in case of SchemaNotFoundException. 
What do you think?
