### ISSUE TITLE
Offset committing to kafka issue

### ISSUE THREAD

**Issue by dankraw** [allegro/hermes#189]
There is an issue with committing offsets to kafka, might be related to stacktrace we've stumbled upon. 

```
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method)
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.write(IOUtil.java:148)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504)
	at java.nio.channels.SocketChannel.write(SocketChannel.java:502)
	at kafka.network.BoundedByteBufferSend.writeTo(BoundedByteBufferSend.scala:56)
	at kafka.network.Send$class.writeCompletely(Transmission.scala:75)
	at kafka.network.BoundedByteBufferSend.writeCompletely(BoundedByteBufferSend.scala:26)
	at kafka.network.BlockingChannel.send(BlockingChannel.scala:103)
	at pl.allegro.tech.hermes.consumers.consumer.offset.kafka.broker.BrokerOffsetsRepository.commitOffset(BrokerOffsetsRepository.java:87)
	at pl.allegro.tech.hermes.consumers.consumer.offset.kafka.broker.BrokerOffsetsRepository.save(BrokerOffsetsRepository.java:72)
	at pl.allegro.tech.hermes.consumers.consumer.receiver.kafka.broker.BrokerMessageCommitter.commitOffset(BrokerMessageCommitter.java:22)
	at pl.allegro.tech.hermes.consumers.consumer.offset.OffsetCommitter.run(OffsetCommitter.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by sukumarch3** [comment]
Hi, We are facing this same issue, Can you please share the details about this fix? how can I get it fixed?.

Thanks.
