### ISSUE TITLE
Fetch topic schema eagerly

### ISSUE THREAD

**Issue by dankraw** [allegro/hermes#200]
We should consider fetching topic schema eagerly. 
Right now, every first request to validated topic ends with a `408 Request timeout response`:
```
{
  "message": "Async timeout, cause: unknown",
  "code": "TIMEOUT"
}
```
```
2015-08-31 09:30:26.260 ERROR p.a.t.h.f.publishing.HttpResponder - Async timeout, cause: unknown, publishing on topic g1.t, remote host 0:0:0:0:0:0:0:1, message state PARSED
```
This applies to **zookeeper**-based schema repository as well.

**Comment by kjetilhp** [comment]
Not sure if this is related, but I'm getting this error everytime I try out the getting startet guide, fails on the last step when posting to the sample topic. And nothing is ever sent further to the request.in 
```javascript
➜  hermes  curl -v -d '{"id": 12345, "page": "main"}' http://192.168.99.100:8888/topics/com.example.events.clicks
*   Trying 192.168.99.100...
* Connected to 192.168.99.100 (192.168.99.100) port 8888 (#0)
> POST /topics/com.example.events.clicks HTTP/1.1
> Host: 192.168.99.100:8888
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Length: 29
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 29 out of 29 bytes
< HTTP/1.1 408 Request Time-out
< Hermes-Message-Id: fa0f85e3-b1ac-4cf5-bdb8-7a3b476c99c9
< Content-Type: application/json;charset=ISO-8859-1
< Content-Length: 60
< Date: Thu, 24 Sep 2015 06:41:58 GMT
<
* Connection #0 to host 192.168.99.100 left intact
{"message":"Async timeout, cause: unknown","code":"TIMEOUT"}%
´´´

**Comment by adamdubiel** [comment]
Did you try sending more messages? It might be that first message times out since we have to pull topic metadata from Kafka.

**Comment by kjetilhp** [comment]
Tried several messages, same result. Did the setup both on my mac an on a linux server, same behavior.

**Comment by adamdubiel** [comment]
Can you take a look at `hermes-frontend` container logs? It might have not connected to Kafka at all..

**Comment by kjetilhp** [comment]
Seems like the last state is reconnected. Though it says "broker my be down"

Logs:
```javascript
2015-09-23 21:18:22.439 INFO  c.n.c.sources.URLConfigurationSource - URLs to be used as dynamic configuration source: [file:/etc/hermes/frontend.properties]
2015-09-23 21:18:22.465 INFO  c.n.config.DynamicPropertyFactory - DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@13acb0d1
2015-09-23 21:18:22.532 INFO  o.a.c.f.imps.CuratorFrameworkImpl - Starting
2015-09-23 21:18:22.608 INFO  o.a.c.f.state.ConnectionStateManager - State change: CONNECTED
2015-09-23 21:18:23.006 INFO  o.a.k.c.producer.ProducerConfig - ProducerConfig values:
	compression.type = snappy
	metric.reporters = []
	metadata.max.age.ms = 300000
	metadata.fetch.timeout.ms = 500
	acks = 1
	batch.size = 16384
	reconnect.backoff.ms = 10
	bootstrap.servers = [kafka:9092]
	receive.buffer.bytes = 32768
	retry.backoff.ms = 256
	buffer.memory = 268435456
	timeout.ms = 1000
	key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	retries = 2147483647
	max.request.size = 1048576
	block.on.buffer.full = false
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	metrics.sample.window.ms = 30000
	send.buffer.bytes = 131072
	max.in.flight.requests.per.connection = 5
	metrics.num.samples = 2
	linger.ms = 0
	client.id =

2015-09-23 21:18:23.060 INFO  o.a.k.c.producer.ProducerConfig - ProducerConfig values:
	compression.type = snappy
	metric.reporters = []
	metadata.max.age.ms = 300000
	metadata.fetch.timeout.ms = 500
	acks = -1
	batch.size = 16384
	reconnect.backoff.ms = 10
	bootstrap.servers = [kafka:9092]
	receive.buffer.bytes = 32768
	retry.backoff.ms = 256
	buffer.memory = 268435456
	timeout.ms = 1000
	key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	retries = 2147483647
	max.request.size = 1048576
	block.on.buffer.full = false
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	metrics.sample.window.ms = 30000
	send.buffer.bytes = 131072
	max.in.flight.requests.per.connection = 5
	metrics.num.samples = 2
	linger.ms = 0
	client.id =

2015-09-23 21:18:23.166 INFO  org.xnio - XNIO version 3.3.1.Final
2015-09-23 21:18:23.175 INFO  org.xnio.nio - XNIO NIO Implementation Version 3.3.1.Final
2015-09-24 05:50:18.339 INFO  o.a.c.f.state.ConnectionStateManager - State change: SUSPENDED
2015-09-24 05:50:20.032 INFO  o.a.c.f.state.ConnectionStateManager - State change: LOST
2015-09-24 05:50:20.032 WARN  org.apache.curator.ConnectionState - Session expired event received
2015-09-24 05:50:20.038 INFO  o.a.c.f.state.ConnectionStateManager - State change: RECONNECTED
2015-09-24 06:29:25.819 INFO  p.a.t.h.c.cache.zookeeper.NodeCache - Got entry change event for path /run/hermes/groups/com.example.events
2015-09-24 06:30:30.607 INFO  p.a.t.h.f.c.t.z.TopicsNodeCache - Got topic change event for path /run/hermes/groups/com.example.events/topics/clicks type CHILD_ADDED
2015-09-24 06:33:37.010 ERROR p.a.t.h.f.publishing.HttpResponder - Async timeout, cause: unknown, publishing on topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA_PRODUCER_QUEUE
2015-09-24 06:33:37.478 WARN  p.a.t.h.f.publishing.HttpResponder - Response already sent. Error message Broker seems to be down, cause: Failed to update metadata after 500 ms., topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA
2015-09-24 06:40:25.324 ERROR p.a.t.h.f.publishing.HttpResponder - Async timeout, cause: unknown, publishing on topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA_PRODUCER_QUEUE
2015-09-24 06:40:25.765 WARN  p.a.t.h.f.publishing.HttpResponder - Response already sent. Error message Broker seems to be down, cause: Failed to update metadata after 500 ms., topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA
2015-09-24 06:41:53.982 ERROR p.a.t.h.f.publishing.HttpResponder - Async timeout, cause: unknown, publishing on topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA_PRODUCER_QUEUE
2015-09-24 06:41:54.417 WARN  p.a.t.h.f.publishing.HttpResponder - Response already sent. Error message Broker seems to be down, cause: Failed to update metadata after 500 ms., topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA
2015-09-24 06:41:54.811 ERROR p.a.t.h.f.publishing.HttpResponder - Async timeout, cause: unknown, publishing on topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA_PRODUCER_QUEUE
2015-09-24 06:41:55.240 WARN  p.a.t.h.f.publishing.HttpResponder - Response already sent. Error message Broker seems to be down, cause: Failed to update metadata after 500 ms., topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA
2015-09-24 06:41:55.680 ERROR p.a.t.h.f.publishing.HttpResponder - Async timeout, cause: unknown, publishing on topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA_PRODUCER_QUEUE
2015-09-24 06:41:56.116 WARN  p.a.t.h.f.publishing.HttpResponder - Response already sent. Error message Broker seems to be down, cause: Failed to update metadata after 500 ms., topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA
2015-09-24 06:41:58.717 ERROR p.a.t.h.f.publishing.HttpResponder - Async timeout, cause: unknown, publishing on topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA_PRODUCER_QUEUE
2015-09-24 06:41:59.153 WARN  p.a.t.h.f.publishing.HttpResponder - Response already sent. Error message Broker seems to be down, cause: Failed to update metadata after 500 ms., topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA
2015-09-24 07:25:07.668 ERROR p.a.t.h.f.publishing.HttpResponder - Async timeout, cause: unknown, publishing on topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA_PRODUCER_QUEUE
2015-09-24 07:25:08.104 WARN  p.a.t.h.f.publishing.HttpResponder - Response already sent. Error message Broker seems to be down, cause: Failed to update metadata after 500 ms., topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA
2015-09-24 07:25:20.599 ERROR p.a.t.h.f.publishing.HttpResponder - Async timeout, cause: unknown, publishing on topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA_PRODUCER_QUEUE
2015-09-24 07:25:21.037 WARN  p.a.t.h.f.publishing.HttpResponder - Response already sent. Error message Broker seems to be down, cause: Failed to update metadata after 500 ms., topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA
2015-09-24 07:25:26.967 ERROR p.a.t.h.f.publishing.HttpResponder - Async timeout, cause: unknown, publishing on topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA_PRODUCER_QUEUE
2015-09-24 07:25:27.403 WARN  p.a.t.h.f.publishing.HttpResponder - Response already sent. Error message Broker seems to be down, cause: Failed to update metadata after 500 ms., topic com.example.events.clicks, remote host 192.168.99.1, message state SENDING_TO_KAFKA
´´´

**Comment by adamdubiel** [comment]
Exactly as i though - there is some connection issue here. Docker is a pain when trying to connect multiple containers :/ @dankraw can you help us out?

**Comment by dankraw** [comment]
First thing you should do is to change `KAFKA_ADVERTISED_HOST_NAME` in `docker-compose.yml` to your docker interface, did you try it?

**Comment by kjetilhp** [comment]
Done, changed it to 192.168.99.100 but same results in the log

**Comment by dankraw** [comment]
OK, try removing the old containers and creating new ones, if you haven't already.

**Comment by kjetilhp** [comment]
did docker rm on all containers and docker-compose up -d again, same result.

**Comment by dankraw** [comment]
I would try one more thing, setting the `KAFKA_ADVERTISED_HOST_NAME` to your eth0 interface, and rebuilding the containers. If there's no success, I would give up and try bare hermes + kafka, without docker, which on some installations is very hard to debug. 
I personally tried it on ubuntu 14.04 and MacOS Yosemite + boot2docker and it all worked, but I know a friend of mine didn't make it on his Linux. You can look at this issue, that is directly related to your problem: https://github.com/allegro/hermes/issues/140, running docker on vagrant solved the problem. ;)

**Comment by kjetilhp** [comment]
From the logs (on my mac) it seems to try connecting to 192.168.99.1 instead of 192.168.99.100 after updating the env variable. Trying now to start from scratch on my linux box with the env variable set to the public interface address.

**Comment by kjetilhp** [comment]
No luck on ubuntu box, can telnet 9092 on the ip set for the kafka env variable but logs in frontend container still reports timeout on the same ip.

**Comment by dankraw** [comment]
It might be some docker-compose or firewall-related issue, hard to say (you can tell us what docker/docker-compose versions you use). 
If you want to try hermes, I would suggest running it straight from your IDE (frontend, management and consumers modules have their respective runnable Main classes) or by building your own distZips with `./gradlew -q clean distZip -Pdistribution`, unzipping and running them.

**Comment by kjetilhp** [comment]
just upgraded now to compose 1.4.2 on the Ubuntu box, forgot the -d on startup so got the full logs.. and here it seems that something else is wrong and that the message is hitting Kafka. Haven't been able to do a successful compile of the git project yet, but I'll try on my mac later..
Kafka logs:
```javascript
frontend_1   | 2015-09-24 13:13:35.146 ERROR p.a.t.h.f.publishing.HttpResponder - Async timeout, cause: unknown, publishing on topic com.example.events.clicks, remote host 10.0.1.100, message state SENDING_TO_KAFKA_PRODUCER_QUEUE
kafka_1      | [2015-09-24 13:13:35,146] ERROR [KafkaApi-9092] error when handling request ConsumerMetadataRequest(com.example.events_clicks_clicks-receiver,0,0,) (kafka.server.KafkaApis)
kafka_1      | kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
kafka_1      | 	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:70)
kafka_1      | 	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:171)
kafka_1      | 	at kafka.server.KafkaApis$$anonfun$19.apply(KafkaApis.scala:513)
kafka_1      | 	at kafka.server.KafkaApis$$anonfun$19.apply(KafkaApis.scala:503)
kafka_1      | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
kafka_1      | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
kafka_1      | 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
kafka_1      | 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
kafka_1      | 	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
kafka_1      | 	at scala.collection.SetLike$class.map(SetLike.scala:93)
kafka_1      | 	at scala.collection.AbstractSet.map(Set.scala:47)
kafka_1      | 	at kafka.server.KafkaApis.getTopicMetadata(KafkaApis.scala:503)
kafka_1      | 	at kafka.server.KafkaApis.handleConsumerMetadataRequest(KafkaApis.scala:607)
kafka_1      | 	at kafka.server.KafkaApis.handle(KafkaApis.scala:69)
kafka_1      | 	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:59)
kafka_1      | 	at java.lang.Thread.run(Thread.java:701)
frontend_1   | 2015-09-24 13:13:35.627 WARN  p.a.t.h.f.publishing.HttpResponder - Response already sent. Error message Broker seems to be down, cause: Failed to update metadata after 500 ms., topic com.example.events.clicks, remote host 10.0.1.100, message state SENDING_TO_KAFKA
kafka_1      | [2015-09-24 13:13:36,148] ERROR [KafkaApi-9092] error when handling request ConsumerMetadataRequest(com.example.events_clicks_clicks-receiver,0,0,) (kafka.server.KafkaApis)
kafka_1      | kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
kafka_1      | 	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:70)
kafka_1      | 	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:171)
kafka_1      | 	at kafka.server.KafkaApis$$anonfun$19.apply(KafkaApis.scala:513)
kafka_1      | 	at kafka.server.KafkaApis$$anonfun$19.apply(KafkaApis.scala:503)
kafka_1      | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
kafka_1      | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
kafka_1      | 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
kafka_1      | 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
kafka_1      | 	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
kafka_1      | 	at scala.collection.SetLike$class.map(SetLike.scala:93)
kafka_1      | 	at scala.collection.AbstractSet.map(Set.scala:47)
kafka_1      | 	at kafka.server.KafkaApis.getTopicMetadata(KafkaApis.scala:503)
kafka_1      | 	at kafka.server.KafkaApis.handleConsumerMetadataRequest(KafkaApis.scala:607)
kafka_1      | 	at kafka.server.KafkaApis.handle(KafkaApis.scala:69)
kafka_1      | 	at kafka.server.KafkaRequestHandler.run(KafkaRequestHandler.scala:59)
kafka_1      | 	at java.lang.Thread.run(Thread.java:701)
kafka_1      | [2015-09-24 13:13:37,151] ERROR [KafkaApi-9092] error when handling request ConsumerMetadataRequest(com.example.events_clicks_clicks-receiver,0,0,) (kafka.server.KafkaApis)
kafka_1      | kafka.admin.AdminOperationException: replication factor: 3 larger than available brokers: 1
kafka_1      | 	at kafka.admin.AdminUtils$.assignReplicasToBrokers(AdminUtils.scala:70)
kafka_1      | 	at kafka.admin.AdminUtils$.createTopic(AdminUtils.scala:171)
kafka_1      | 	at kafka.server.KafkaApis$$anonfun$19.apply(KafkaApis.scala:513)
kafka_1      | 	at kafka.server.KafkaApis$$anonfun$19.apply(KafkaApis.scala:503)
kafka_1      | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
kafka_1      | 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
kafka_1      | 	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
kafka_1      | 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
kafka_1      | 	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
kafka_1      | 	at scala.collection.SetLike$class.map(SetLike.scala:93)
´´´

**Comment by neerajBaji** [comment]
@kjetilhp - hi, were you able to find a solution for this issue?

**Comment by kjetilhp** [comment]
no, tried again last week to see if they fixed the images but no luck, have to do a manual build as suggested.

**Comment by dankraw** [comment]
@kjetilhp @neerajBaji I've created an issue #258, we will look at this as soon as possible. I believe this will make running Hermes for the first time much easier.
