### ISSUE TITLE
Broker seems to be down

### ISSUE THREAD

**Issue by tycho01** [allegro/hermes#33]
Going through the [tutorial](http://hermes-pubsub.readthedocs.org/en/latest/contents/tutorials/01_getting_started.html), interacting with groups/topics/subscriptions worked fine for me. At the last step of publishing though (the first step at port `:8888`), I'm met with an HTTP 500 error: `{"message":"Broker seems to be down, cause: Failed to update metadata after 500 ms.","code":"INTERNAL_ERROR"}`. However, trying to access `:8888` by browser, it yields me a `http://localhost:8888/status/health` with content `UP`. Maybe this relates to Kafka settings like [`topic.metadata.refresh.interval.ms`](https://kafka.apache.org/08/configuration.html), which apparently had a default value of 600 * 1000 (i.e. 1200 times as much). I hadn't changed anything, so not sure why it's 500, though on localhost I'd expect this 500 ms should suffice... What might be a good way to debug this?

**Comment by adamdubiel** [comment]
And is your Kafka docker alive?

**Comment by tycho01** [comment]
Restarted the Kafka docker just in case, one error in the log (from the restart), below. `:8080` interactions still work, `:8888` publishes still yield the above error, though neither leave traces in the log.

```
[2015-05-27 12:49:26,000] INFO Verifying properties (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,026] INFO Property advertised.host.name is overridden to 192.168.59.103 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,026] INFO Property advertised.port is overridden to 9092 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,026] INFO Property broker.id is overridden to 9092 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,027] INFO Property log.cleaner.enable is overridden to false (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,027] INFO Property log.dirs is overridden to /kafka/kafka-logs-9092 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,027] INFO Property log.retention.check.interval.ms is overridden to 300000 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,027] INFO Property log.retention.hours is overridden to 168 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,027] INFO Property log.segment.bytes is overridden to 1073741824 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,027] INFO Property num.io.threads is overridden to 8 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,027] INFO Property num.network.threads is overridden to 3 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,028] INFO Property num.partitions is overridden to 1 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,028] INFO Property num.recovery.threads.per.data.dir is overridden to 1 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,028] INFO Property port is overridden to 9092 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,028] INFO Property socket.receive.buffer.bytes is overridden to 102400 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,029] INFO Property socket.request.max.bytes is overridden to 104857600 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,029] INFO Property socket.send.buffer.bytes is overridden to 102400 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,029] INFO Property zookeeper.connect is overridden to 172.17.0.9:2181 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,029] INFO Property zookeeper.connection.timeout.ms is overridden to 6000 (kafka.utils.VerifiableProperties)
[2015-05-27 12:49:26,061] INFO [Kafka Server 9092], starting (kafka.server.KafkaServer)
[2015-05-27 12:49:26,063] INFO [Kafka Server 9092], Connecting to zookeeper on 172.17.0.9:2181 (kafka.server.KafkaServer)
[2015-05-27 12:49:26,076] INFO Starting ZkClient event thread. (org.I0Itec.zkclient.ZkEventThread)
[2015-05-27 12:49:26,077] INFO Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,077] INFO Client environment:host.name=2d54c47ba03d (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,077] INFO Client environment:java.version=1.6.0_34 (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,077] INFO Client environment:java.vendor=Sun Microsystems Inc. (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,077] INFO Client environment:java.home=/usr/lib/jvm/java-6-openjdk-amd64/jre (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,077] INFO Client environment:java.class.path=:/opt/kafka_2.10-0.8.2.0/bin/../core/build/dependant-libs-2.10.4*/*.jar:/opt/kafka_2.10-0.8.2.0/bin/../examples/build/libs//kafka-examples*.jar:/opt/kafka_2.10-0.8.2.0/bin/../contrib/hadoop-consumer/build/libs//kafka-hadoop-consumer*.jar:/opt/kafka_2.10-0.8.2.0/bin/../contrib/hadoop-producer/build/libs//kafka-hadoop-producer*.jar:/opt/kafka_2.10-0.8.2.0/bin/../clients/build/libs/kafka-clients*.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/jopt-simple-3.2.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/kafka-clients-0.8.2.0.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/kafka_2.10-0.8.2.0-javadoc.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/kafka_2.10-0.8.2.0-scaladoc.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/kafka_2.10-0.8.2.0-sources.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/kafka_2.10-0.8.2.0-test.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/kafka_2.10-0.8.2.0.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/log4j-1.2.16.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/lz4-1.2.0.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/metrics-core-2.2.0.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/scala-library-2.10.4.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/slf4j-api-1.7.6.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/slf4j-log4j12-1.6.1.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/snappy-java-1.1.1.6.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/zkclient-0.3.jar:/opt/kafka_2.10-0.8.2.0/bin/../libs/zookeeper-3.4.6.jar:/opt/kafka_2.10-0.8.2.0/bin/../core/build/libs/kafka_2.10*.jar (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,077] INFO Client environment:java.library.path=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64/server:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/amd64:/usr/lib/jvm/java-6-openjdk-amd64/jre/../lib/amd64:/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,077] INFO Client environment:java.io.tmpdir=/tmp (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,077] INFO Client environment:java.compiler=<NA> (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,077] INFO Client environment:os.name=Linux (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,077] INFO Client environment:os.arch=amd64 (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,077] INFO Client environment:os.version=3.13.0-53-generic (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,078] INFO Client environment:user.name=root (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,078] INFO Client environment:user.home=/root (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,078] INFO Client environment:user.dir=/ (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,079] INFO Initiating client connection, connectString=172.17.0.9:2181 sessionTimeout=6000 watcher=org.I0Itec.zkclient.ZkClient@11c757a1 (org.apache.zookeeper.ZooKeeper)
[2015-05-27 12:49:26,098] INFO Opening socket connection to server 172.17.0.9/172.17.0.9:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2015-05-27 12:49:26,103] INFO Socket connection established to 172.17.0.9/172.17.0.9:2181, initiating session (org.apache.zookeeper.ClientCnxn)
[2015-05-27 12:49:26,141] INFO Session establishment complete on server 172.17.0.9/172.17.0.9:2181, sessionid = 0x14d9540c1860008, negotiated timeout = 6000 (org.apache.zookeeper.ClientCnxn)
[2015-05-27 12:49:26,142] INFO zookeeper state changed (SyncConnected) (org.I0Itec.zkclient.ZkClient)
[2015-05-27 12:49:26,309] INFO Loading logs. (kafka.log.LogManager)
[2015-05-27 12:49:26,314] INFO Logs loading complete. (kafka.log.LogManager)
[2015-05-27 12:49:26,314] INFO Starting log cleanup with a period of 300000 ms. (kafka.log.LogManager)
[2015-05-27 12:49:26,317] INFO Starting log flusher with a default period of 9223372036854775807 ms. (kafka.log.LogManager)
[2015-05-27 12:49:26,349] INFO Awaiting socket connections on 0.0.0.0:9092. (kafka.network.Acceptor)
[2015-05-27 12:49:26,351] INFO [Socket Server on Broker 9092], Started (kafka.network.SocketServer)
[2015-05-27 12:49:26,403] INFO Will not load MX4J, mx4j-tools.jar is not in the classpath (kafka.utils.Mx4jLoader$)
[2015-05-27 12:49:26,450] INFO conflict in /brokers/ids/9092 data: {"jmx_port":-1,"timestamp":"1432730966434","host":"192.168.59.103","version":1,"port":9092} stored data: {"jmx_port":-1,"timestamp":"1432728168765","host":"192.168.59.103","version":1,"port":9092} (kafka.utils.ZkUtils$)
[2015-05-27 12:49:26,482] INFO I wrote this conflicted ephemeral node [{"jmx_port":-1,"timestamp":"1432730966434","host":"192.168.59.103","version":1,"port":9092}] at /brokers/ids/9092 a while back in a different session, hence I will backoff for this node to be deleted by Zookeeper and retry (kafka.utils.ZkUtils$)
[2015-05-27 12:49:32,018] ERROR Error handling event ZkEvent[Data of /controller changed sent to kafka.server.ZookeeperLeaderElector$LeaderChangeListener@30d7c1ba] (org.I0Itec.zkclient.ZkEventThread)
java.lang.IllegalStateException: Kafka scheduler has not been started
	at kafka.utils.KafkaScheduler.ensureStarted(KafkaScheduler.scala:114)
	at kafka.utils.KafkaScheduler.shutdown(KafkaScheduler.scala:86)
	at kafka.controller.KafkaController.onControllerResignation(KafkaController.scala:350)
	at kafka.controller.KafkaController$$anonfun$2.apply$mcV$sp(KafkaController.scala:162)
	at kafka.server.ZookeeperLeaderElector$LeaderChangeListener$$anonfun$handleDataDeleted$1.apply$mcZ$sp(ZookeeperLeaderElector.scala:138)
	at kafka.server.ZookeeperLeaderElector$LeaderChangeListener$$anonfun$handleDataDeleted$1.apply(ZookeeperLeaderElector.scala:134)
	at kafka.server.ZookeeperLeaderElector$LeaderChangeListener$$anonfun$handleDataDeleted$1.apply(ZookeeperLeaderElector.scala:134)
	at kafka.utils.Utils$.inLock(Utils.scala:535)
	at kafka.server.ZookeeperLeaderElector$LeaderChangeListener.handleDataDeleted(ZookeeperLeaderElector.scala:134)
	at org.I0Itec.zkclient.ZkClient$6.run(ZkClient.java:549)
	at org.I0Itec.zkclient.ZkEventThread.run(ZkEventThread.java:71)
[2015-05-27 12:49:32,492] INFO Registered broker 9092 at path /brokers/ids/9092 with address 192.168.59.103:9092. (kafka.utils.ZkUtils$)
[2015-05-27 12:49:32,529] INFO [Kafka Server 9092], started (kafka.server.KafkaServer)
```

**Comment by pjagielski** [comment]
Are you using boot2docker?

**Comment by tycho01** [comment]
I'm using Docker within an Ubuntu Trusty VM, through VirtualBox in a W8 host.

**Comment by pjagielski** [comment]
Ok, so I think you should set `KAFKA_ADVERTISED_HOST_NAME` in `docker-compose` to your machine's IP, as said in https://github.com/wurstmeister/kafka-docker#pre-requisites

**Comment by tycho01** [comment]
Right, thank you, that's probably it... I've tried a few different things, though no dice so far.

```
#    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.103 # default, :8888 fails
#    KAFKA_ADVERTISED_HOST_NAME: localhost # first plan, but :8888 still fails
#    KAFKA_ADVERTISED_HOST_NAME: 14.145.253.49 # public IP (though in VM), :8080/:8888 both fail
#    KAFKA_ADVERTISED_HOST_NAME: 10.0.2.15 # internal IP as found in ifconfig -> eth0, :8888 fails
    KAFKA_ADVERTISED_HOST_NAME: 172.17.42.1 # internal IP as found in ifconfig -> docker0, :8888 fails
```

I imagine the VM is complicating things, so I'd gladly try in my W8 host's boot2docker as well... but getting Java onto that is still turning out quite a challenge so far (it seems on a restart everything gets wiped). For the VM, should it require port-forwarding voodoo to make it work?

**Comment by dankraw** [comment]
I got it working on Ubuntu 14.04 LTS VM. 

The correct setup is:
```
 KAFKA_ADVERTISED_HOST_NAME: 172.17.42.1 # internal IP as found in ifconfig -> docker0
```
Note that you should remove the old containers before building new ones:
 ``` 
docker rm `docker ps -aq --no-trunc`
./build.sh
./run.sh 
```
Tell us if it helped.

**Comment by tycho01** [comment]
Rebuilding that way did it for me, thank you for your assistance! :D

**Comment by jak3chase** [comment]
Using upio's's forked example, I get a lot of errors that look like:
WARN state.ConnectionStateManager: There are no ConnectionStateListeners registered.

ERROR producer.SyncProducer: Producer connection to localhost:49155 unsuccessful
java.net.ConnectException: Connection refused

I think I am using the correct IP, the one from docker0 in ifconfig. I've also tried a bunch of IPs (eth0 etc).

Any ideas?
