### ISSUE TITLE
Getting SSL exception on starting consumers

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#433]
I have build a custom consumer as described in the documents (based on spring boot). I am getting below exceptions. I believe there are no SSL configurations for consumers. I am running frontend with SSL/http2   enabled  

java.lang.IllegalStateException: SSL doesn't have a valid keystore

Complete logs : http://pastebin.com/gG2v0Ww6

**Comment by hikrrish** [comment]
usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-2.b17.7.amzn1.x86_64/jre/lib/security/cacerts is not a valid keystore 

logs :
2016-04-05 16:35:56.506 INFO  o.a.c.f.state.ConnectionStateManager - State change: CONNECTED
2016-04-05 16:35:57.060 INFO  org.eclipse.jetty.util.log - Logging initialized @3209ms
2016-04-05 16:35:57.122 WARN  o.e.j.u.component.AbstractLifeCycle - FAILED SslContextFactory@6f2a0a0d(null,/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-2.b17.7.amzn1.x86_64/jre/lib/security/cacerts): java.lang.IllegalStateException: SSL doesn't have a valid keystore
java.lang.IllegalStateException: SSL doesn't have a valid keystore
        at org.eclipse.jetty.util.ssl.SslContextFactory.checkKeyStore(SslContextFactory.java:997)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:271)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
        at org.eclipse.jetty.client.HttpClient.doStart(HttpClient.java:229)

**Comment by dankraw** [comment]
Hello, you need to provide path to the JRE truststore location using `javax.net.ssl.*` properties. See: http://hermes-pubsub.readthedocs.org/en/latest/configuration/secure-transport/#consumers-ssl

**Comment by hikrrish** [comment]
I think it is using the correct path ( default one )

usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-2.b17.7.amzn1.x86_64/jre/lib/security/cacerts is not a valid keystore


keytool -list -keystore /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-2.b17.7.amzn1.x86_64/jre/lib/security/cacerts
Enter keystore password:

Keystore type: JKS
Keystore provider: SUN

Your keystore contains 159 entries

Tried with my own created keystore and getting same problem

**Comment by dankraw** [comment]
It looks like you have a custom Jetty version on classpath, could you stick to the one Hermes comes with (v9.3.6.v20151106)?

**Comment by hikrrish** [comment]
I am using  hermes consumers 0.8.6  from maven 
		<dependency>
			<groupId>pl.allegro.tech.hermes</groupId>
			<artifactId>hermes-consumers</artifactId>
			<version>0.8.6</version>
		</dependency>

It has transitive dependency on jetty-io/ jetty-util/ jetty-http/ jetty-client 9.2.15.v20160210. I have not added any custom jetty version here. do you suggest trying with v9.3.6.v20151106 ?

**Comment by dankraw** [comment]
Looks like you're right about the dependency (it's weird), but it would be good to force Jetty v9.3.6 somehow. Maybe this will work for you. I'm looking at the v9.2.15 source code - you are forced to have key store set explicitly before setting trust store, that's where the exception comes from.

I think we need to have a deeper look at the issue.

**Comment by hikrrish** [comment]
well I forced jetty client version to v9.3.6.v20151106 still having same issue with 0.8.6 build using maven. I am running 0.8.7-SNAPSHOT on a different instance and its running fine

**Comment by hikrrish** [comment]
This is happening when I am trying to run a uber jar using spring boot gradle plugin. looks like adding spring boot is making difference here.

**Comment by hikrrish** [comment]
Tried with the same keystore.jks file on which frontend is running and supporting https

2016-04-07 04:53:20.733 INFO  o.a.c.f.state.ConnectionStateManager - State change: CONNECTED
2016-04-07 04:53:21.153 INFO  org.eclipse.jetty.util.log - Logging initialized @1477ms
2016-04-07 04:53:21.183 WARN  o.e.j.u.component.AbstractLifeCycle - FAILED SslContextFactory@347bdeef(null,/opt/hermes/conf/keystore.jks): java.lang.IllegalStateException: SSL doesn't have a valid keystore
java.lang.IllegalStateException: SSL doesn't have a valid keystore

Still same issue

**Comment by dankraw** [comment]
`java.lang.IllegalStateException: SSL doesn't have a valid keystore` - this is a Jetty 9.2.15 error actually, not v9.3.6 - you haven't successfully forced v9.3.6. 

The consumers `HttpClientFactory` that configures the Jetty sender's SSL context hasn't changed since `hermes-0.8.4`, so if you have no problems with `0.8.7-SNAPSHOT` I would guess you use some different project setup and use Jetty 9.3.6 which is fine. :)

**Comment by hikrrish** [comment]
@dankraw  Many thanks problem solved 
I actually forced jetty client to  v9.3.6 and it again pulled up jetty-io/ jetty-util/ jetty-http 9.2.15

Now I have forced all the jetty libraries  above to  v9.3.6 

Please close this thread

**Comment by adamdubiel** [comment]
Happy to do it :)

**Comment by dankraw** [comment]
@hikrrish You're welcome, I'm happy it worked for you. :)
