### ISSUE TITLE
Adding ConsulAware EndPoint 

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#470]
This is in reference to #426  
Based on the suggestion we implemented our own resolver for service:// to resolve consul end points. However, it seems management doesn't allow any subscriptions besides http/https and jms.

Will I need to provide any sort of startup hooks to management in order support my own protocol?

**Comment by adamdubiel** [comment]
I see that the docs are missing, but this is actually in place. You can make Management recognize custom protocol by specifying a Spring Boot/yaml list:

```
subscription:
  additionalEndpointProtocols: service
```

**Comment by hikrrish** [comment]
Thanks

**Comment by hikrrish** [comment]
Thanks Adam for a quick response :)

**Comment by hikrrish** [comment]
@adamdubiel 

Strangely, we are getting below exception during consumers start up

 ```
Failed to create consumer for subscription myhost_account_mySubscription__test__3
pl.allegro.tech.hermes.common.exception.EndpointProtocolNotSupportedException: Protocol service not supported in endpoint EndpointAddress{endpoint=service://myhost.myhost.com/endpoint}
        at pl.allegro.tech.hermes.consumers.consumer.sender.MessageSenderFactory.create(MessageSenderFactory.java:34)
        at pl.allegro.tech.hermes.consumers.consumer.ConsumerMessageSender.<init>(ConsumerMessageSender.java:54)
        at pl.allegro.tech.hermes.consumers.consumer.ConsumerMessageSenderFactory.create(ConsumerMessageSenderFactory.java:71)
        at pl.allegro.tech.hermes.consumers.supervisor.ConsumerFactory.createConsumer(ConsumerFactory.java:105)
        at pl.allegro.tech.hermes.consumers.supervisor.ConsumersSupervisor.createAndExecuteConsumer(ConsumersSupervisor.java:206)
        at pl.allegro.tech.hermes.consumers.supervisor.ConsumersSupervisor.createAndExecuteConsumerIfNotExists(ConsumersSupervisor.java:180)
        at pl.allegro.tech.hermes.consumers.supervisor.ConsumersSupervisor.assignConsumerForSubscription(ConsumersSupervisor.java:84)
        at pl.allegro.tech.hermes.consumers.supervisor.workload.mirror.LegacyMirroringSupervisorController.onSubscriptionCreated(LegacyMirroringSupervisorController.java:36)
        at pl.allegro.tech.hermes.consumers.subscription.cache.zookeeper.SubscriptionsNodeCache.lambda$childEvent$56(SubscriptionsNodeCache.java:55)
        at pl.allegro.tech.hermes.common.cache.queue.QueueTask.run(QueueTask.java:16)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

```

The following is the startup hook configured for consul aware endpoint 


```
.withMessageSenderProvider(
                "service",
                (s) -> new JettyHttpMessageSenderProvider(s.getService(HttpClient.class), new ConfigFactory(),
                    consulAwareServiceEndPointResolver, new DefaultHttpMetadataAppender()))
```

We think for some reason the new protocol is not on the messageSendersProviders map

**Comment by adamdubiel** [comment]
Yes, you are right, it must not have made it there, which is quite weird - we use it and it works in our case. Is there any other part of related configuration that could break it? Maybe some wrong version has been deployed?

BTW i created PR to document adding custom protocol: https://github.com/allegro/hermes/pull/472

**Comment by gamefundas** [comment]
@adamdubiel  I guess the problem is with Spring cloud consul (DiscoveryServiceClient/LoadbalancedClient - Ribbon) and dependencies that we are using in our ConsulAwareResolver to route the endpoint to a service host. Probably a library conflict, this halts Hermes Consumer to receive subscription information from Zookeeper or reads messages from Kafka. Don't see any errors in the logs to this effect, may be some bean failed to initialize in the Spring boot life cycle or overrides Hermes ones.

Are you using Spring cloud consul or something else to interact with consul discovery? We are using the Spring cloud Brixton release BTW.

**Comment by adamdubiel** [comment]
Oh, thats a complicated setup. We don't use Consumers with Spring. For Consul integration we use [this simple client](https://github.com/Ecwid/consul-api).

**Comment by gamefundas** [comment]
Managed to get it running with Spring cloud Angel. Brixton had some dependency issues. As you said we tried with the Consul Java clients and that works too. 

The only reason we picked up Spring is because we currently have everything running on it. Especially the entire cluster is monitored and administered using Spring admin and other cloud modules. 

I am glad this worked and if this gives any trouble we have the Java clients to fallback.

**Comment by adamdubiel** [comment]
Great to hear it :) I see that you invested quite a lot in Spring. We use it for most of our apps, but it is not mandatory: we have "service contract" in place, which can be implemented on any platform. This is why Hermes is not Spring based in its core.

**Comment by hikrrish** [comment]
Many Thanks Adam .. we have got our custom protocol working. we can close this issue

**Comment by adamdubiel** [comment]
The documentation is now live: http://hermes-pubsub.readthedocs.io/en/latest/configuration/custom-protocol/ , just in case you ever needed it again :)
