### ISSUE TITLE
Elastic search availability for Hermes to deliver messages 

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#570]
In case elastic search is down, messages are not getting delivered to kafka brokers.
@adamdubiel 
We are facing an issue with hermes-consumer/frontend  application where in stops working due to non connectivity with elastic search. 
Is there any dependency on ES availability to get the messages delivered.

logs {

}at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-08-18 00:15:15.635 ERROR p.a.t.hermes.tracker.QueueCommitter - Could not commit batch.
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{11.22.34.56}{elasticsearch.kshost.com/11.22.34.56:9300}]
        at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
        at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
        at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
        at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:283)
        at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:347)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:85)
        at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:59)
        at pl.allegro.tech.hermes.tracker.elasticsearch.ElasticsearchQueueCommitter.processBatch(ElasticsearchQueueCommitter.java:38)
        at pl.allegro.tech.hermes.tracker.QueueCommitter.commit(QueueCommitter.java:39)
        at pl.allegro.tech.hermes.tracker.QueueCommitter.run(QueueCommitter.java:28)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)

**Comment by adamdubiel** [comment]
What version are you referring to? How do you observe lack of messages on Kafka brokers? We have experienced ES outages and it never affected ability to handle Kafka traffic (in & out).

**Comment by hikrrish** [comment]
We  are using 0.8.7 version of hermes along with ES 2.3.3.  ES was down for maintenance 2 weeks back and  it restarted on different IP address with same CNAME. However, consumer and frontend application seems to be caching IP address and trying on the same IP address until restarted. soon after restart we started receiving all the back log messages, only exception I see is related to ES that is why i suspected ES availability.

Also, with above observation it seems like hermes app need a restart in case ES is switched to different IP address.

**Comment by adamdubiel** [comment]
Elastic commits are totally async, meaning documents are pushed onto the queue, which is drained by a scheduled thread. I would suspect some other things - if you would restart your consumers right now, would you also receive load of older messages? Were there any problems with delivery (like subscriber returning 5xx)? Remember, that commits to Kafka can be deferred by a maximum of subscriptions `Message TTL`, if there is a message that can't be delivered.

We haven't testes the "hange cluster ips" scenario - we can look into this one.

**Comment by hikrrish** [comment]
yes, if consumer  is restarted we get a load of messages. There are few warn level logs which may be the cause of this issue 

2016-09-12 02:43:52.928 WARN  k.c.ZookeeperConsumerConnector - [intradayNotification_intradayNotification.rs_ip-10-XX.XX.XX-1473346098835-97bbbfd2], Error while fetching offsets from 10.XX.XX.XX:9092. Possible cause: Received -1 when reading from channel, socket has likely been closed. Possibly consumer not able to fetch the offsets so not able to deliver messages

**Comment by adamdubiel** [comment]
I think you should look into committing offsets in general - do you use filters? Are services that receive messages healthy? Because there should be no huge influx of messages on consumers restart in general.

**Comment by adamdubiel** [comment]
How about this problem? Did you manage to solve it? I will close it, but please reopen it if you need more help.
