### ISSUE TITLE
Exception for consumer offsets in zookeeper

### ISSUE THREAD

**Issue by hikrrish** [allegro/hermes#599]
@adamdubiel 

Started seeing below exception in zookeeper, after which we cleaned up all the zookeeper and kafka nodes thinking that frontend persistence will take care of all the messages. After restart frontend has persisted all the messages (acknowledged by kafka brokers). However consumer doesen't seem to deliver those messages in frontend buffer.  We are using kafka .8.2.2 and 085 hotfix version of hermes consumers.

 [myid:200] - INFO  [ProcessThread(sid:200 cport:-1)::PrepRequestProcessor@651] - Got user-level KeeperException when processing sessionid:0xc857d38211b10017 type:setData cxid:0x116f zxid:0x1000019b5 txntype:-1 reqpath:n/a Error Path:/brokers/topics/__consumer_offsets/partitions/28/state Error:KeeperErrorCode = BadVersion for /brokers/topics/__consumer_offsets/partitions/28/state

**Comment by adamdubiel** [comment]
It looks like some corruption of __consumer_offset topic - i never seen this kind of error message. I don't think this is Hermes problem. BTW what do you mean that you cleaned Zookeeper and Kafka nodes?

**Comment by hikrrish** [comment]
cleaned log dir  for zookeeper and kafka and relied on frontend buffer for message persistence. even after that same issue. I read about  badversion and articles say it can only happen if two process simultaneously modify a znode, whic in our case is here is consumer module, we are running 2 nodes of consumer pointing to same zookeeper cluster. I remember you said that consumer divide the partitions they support so should not be a problem.

**Comment by adamdubiel** [comment]
Yes, there is no problem with this, because of how Kafka does load balancing with multiple consumers (it's Kafka algorithm, not ours :)). Did you stop Kafka & Zookeeper before doing all this magic? And if you cleaned the whole log of ZK - did you not lose Kafka state (topics, offsets etc)?

Anyway, this should go away with restart of Consumers - did you try it? BTW do you have dual or Kafka commit enabled?

**Comment by hikrrish** [comment]
yes, we actually recreated everything., also upgraded kafka to 0.1 and latest hermes API on our test box
now the publisher and management are working fine, I am getting an issue with consumers and it is not able to deliver messages.

Could you suggest what could the cause of this ?


2016-10-19 17:44:17.931 DEBUG p.a.t.h.c.s.p.ConsumerProcessSupervisor - Starting process supervisor loop
2016-10-19 17:44:17.931 DEBUG p.a.t.h.c.s.p.ConsumerProcessSupervisor - Process supervisor loop took 0 ms to check all consumers
2016-10-19 17:44:37.931 DEBUG p.a.t.h.c.s.p.ConsumerProcessSupervisor - Starting process supervisor loop
2016-10-19 17:44:37.931 DEBUG p.a.t.h.c.s.p.ConsumerProcessSupervisor - Process supervisor loop took 0 ms to check all consumers
2016-10-19 17:44:37.963 ERROR p.a.t.h.c.s.m.ConsumersRuntimeMonitor - Could not check correctnes of assignments
java.lang.NullPointerException: null
        at java.util.Collections$UnmodifiableCollection.<init>(Collections.java:1026)
        at java.util.Collections$UnmodifiableSet.<init>(Collections.java:1128)
        at java.util.Collections.unmodifiableSet(Collections.java:1118)
        at pl.allegro.tech.hermes.consumers.supervisor.workload.SubscriptionAssignmentView.getAssignmentsForConsumerNode(SubscriptionAssignmentView.java:75)
        at pl.allegro.tech.hermes.consumers.supervisor.workload.SubscriptionAssignmentView.getSubscriptionsForConsumerNode(SubscriptionAssignmentView.java:71)
        at pl.allegro.tech.hermes.consumers.supervisor.workload.mirror.MirroringSupervisorController.assignedSubscriptions(MirroringSupervisorController.java:127)
        at pl.allegro.tech.hermes.consumers.supervisor.monitor.ConsumersRuntimeMonitor.checkCorrectness(ConsumersRuntimeMonitor.java:46)
        at pl.allegro.tech.hermes.consumers.supervisor.monitor.ConsumersRuntimeMonitor.run(ConsumersRuntimeMonitor.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by adamdubiel** [comment]
This exception is harmless - we should fix it, but it's not something that can affect message sending (this is just a monitoring code, it is run in a separate thread once two minutes).

So what are the symptoms? Do you get any "Lost contact..." or "Restarting" logs? There are no messages coming from consumers at all? Also do you gather metrics?

**Comment by hikrrish** [comment]
Messages are getting published, but not coming back via consumer I have not enabled metrics, though tracking is enabled via custom tracking logger

**Comment by hikrrish** [comment]
Nothing scary in logs however, messages are not getting delivered. Can I paste the logs in paste bin if you take a look what is wrong.  FYI I am using same properties to run consumer which I have used to run 085-hotfix version

**Comment by adamdubiel** [comment]
Hmm okay, you can show us some logs, from the start preferably.

**Comment by hikrrish** [comment]
logs : http://pastebin.com/Xkzy379z
thanks Adam

**Comment by adamdubiel** [comment]
Just to start - can you switch to selective algorithm? i See that you use mirror which should be deprecated.

**Comment by gamefundas** [comment]
@hikrrish can you confirm this fixed the problem. I am assuming it did as we currently don't have any issues open on our side.

**Comment by hikrrish** [comment]
@adamdubiel, we again observed similar issue, resulting consumer not picking up those messages below message first timed out and later published 

2017-08-21 11:21:05.186 WARN  c.w.c.messaging.BrokerTimeoutHandler - Message Id:  0f4b7d8f-c50d-4781-9854-b74393f277b2  timeout by kafka broker on topic: TopicName{name=eventGatewayIVEvent, groupName=otm.cash.cns}
2017-08-21 11:21:05.186 DEBUG n.o.c.map.VanillaChronicleMap - write: 7fb8bb994780
00000000 24 30 66 34 62 37 64 38  66 2D 63 35 30 64 2D 34 $0f4b7d8 f-c50d-4
00000010 37 38 31 2D 39 38 35 34  2D 62 37 34 33 39 33 66 781-9854 -b74393f
2017-08-21 11:21:05.186 INFO  CustomLogRepository - Message Id:0f4b7d8f-c50d-4781-9854-b74393f277b2  inflight by kafka broker on topic: qq and hostname xxx
2017-08-21 11:21:08.396 INFO  CustomLogRepository - Message Id:0f4b7d8f-c50d-4781-9854-b74393f277b2  published by kafka broker on topic: qq and hostname qq

Message got published in 3 seconds but never picked up by consumer 
Could you shed some light why this happened ?

**Comment by arshadansari27** [comment]
Any update on the above exception (Got user-level KeeperException)?

**Comment by druminski** [comment]
Occasionally we still observe this kind of logs in Zookeeper, however Hermes works as expected. Maybe this kind of logs are not so dangerous but further analyses needs to be done. Maybe zookeeper server and client update can help with it. Another solution is to eliminate Zookeeper from Hermes but it is a bigger project for the future. Closing this issue for now.
