### ISSUE TITLE
Exception while creating consumer process

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#654]
```
Consumer process of subscription myGroup.myTopic$mySubscription failed

java.lang.IllegalArgumentException: A metric named output-rate.myGroup.myTopic.mySubscription already exists
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91)
	at pl.allegro.tech.hermes.common.metric.HermesMetrics.registerOutputRateGauge(HermesMetrics.java:93)
	at pl.allegro.tech.hermes.consumers.consumer.rate.SerialConsumerRateLimiter.initialize(SerialConsumerRateLimiter.java:41)
	at pl.allegro.tech.hermes.consumers.consumer.SerialConsumer.initialize(SerialConsumer.java:127)
	at pl.allegro.tech.hermes.consumers.supervisor.process.ConsumerProcess.start(ConsumerProcess.java:120)
	at pl.allegro.tech.hermes.consumers.supervisor.process.ConsumerProcess.run(ConsumerProcess.java:57)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Releasing consumer process thread of subscription myGroup.myTopic$mySubscription
```

When this error occurs then hermes-consumers instance is useless for `mySubscription`. Only restart of whole instance can help.

Discovered on version `0.9.2`

**Comment by druminski** [comment]
Does not occur anymore in newest version of Hermes
