### ISSUE TITLE
max-rate metric already exists

### ISSUE THREAD

**Issue by druminski** [allegro/hermes#773]
Few days ago one of our consumers machine encountered network issues. They lasted about 20 minutes and because of them consumers instance lost contact with kafka, zookeeper, graphite, logs server. After this unreachability most of consumers processes were able to recover. Unfortunately three of them were not. They were restarted indefinitely because of this exceptions:

```
java.lang.IllegalArgumentException: A metric named consumers-rate.max-rate.node.{groupName}.{topicName}.{subscriptionName}.max-rate already exists
        at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91) ~[metrics-core-3.1.1.jar:3.1.1]
        at pl.allegro.tech.hermes.common.metric.HermesMetrics.registerMaxRateGauge(HermesMetrics.java:299) ~[hermes-common-0.11.3.jar:na]
        at pl.allegro.tech.hermes.consumers.consumer.rate.maxrate.NegotiatedMaxRateProvider.start(NegotiatedMaxRateProvider.java:92) ~[hermes-consumers-0.11.3.jar:na]
        at pl.allegro.tech.hermes.consumers.consumer.rate.calculator.OutputRateCalculator.start(OutputRateCalculator.java:62) ~[hermes-consumers-0.11.3.jar:na]
        at pl.allegro.tech.hermes.consumers.consumer.rate.SerialConsumerRateLimiter.initialize(SerialConsumerRateLimiter.java:48) ~[hermes-consumers-0.11.3.jar:na]
        at pl.allegro.tech.hermes.consumers.consumer.SerialConsumer.initialize(SerialConsumer.java:130) ~[hermes-consumers-0.11.3.jar:na]
        at pl.allegro.tech.hermes.consumers.supervisor.process.ConsumerProcess.start(ConsumerProcess.java:127) ~[hermes-consumers-0.11.3.jar:na]
        at pl.allegro.tech.hermes.consumers.supervisor.process.ConsumerProcess.run(ConsumerProcess.java:57) ~[hermes-consumers-0.11.3.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```
Now, as the exception suggests it is about `max-rate` metric which is deregistered in shutdown phase after `output-rate` metric. This means that something bad happened between `output-rate` and `max-rate` metrics deregistration. Unfortunately, I didn't find any logs related to this problem. Only something like this:

```
2017-05-30 04:15:38.995 ERROR p.a.t.h.c.s.p.ConsumerProcessSupervisor - Supervisor failed to process signal Signal{type=STOP, target={groupName.topicName}.${subscriptionName}
java.lang.NullPointerException: null
nn
```

**Comment by druminski** [comment]
This NPE without stack trace bothered me. So I dig a little bit more and I learned that JIT will optimize away stack traces in certain exceptions if they happen enough. More about it can be found [here](http://jawspeak.com/2010/05/26/hotspot-caused-exceptions-to-lose-their-stack-traces-in-production-and-the-fix/). Therefore, I searched logs again and I noticed that there is a lot of NPEs in general but ultimately I found one with a stack trace:

```
2017-05-26 09:39:58.997 ERROR p.a.t.h.c.s.p.ConsumerProcessSupervisor - Supervisor failed to process signal Signal{type=COMMIT, target={groupName.topicName}${subscriptionName}}
java.lang.NullPointerException: null
        at pl.allegro.tech.hermes.consumers.supervisor.process.RunningConsumerProcesses.getProcess(RunningConsumerProcesses.java:32) ~[hermes-consumers-0.11.3.jar:na]
        at pl.allegro.tech.hermes.consumers.supervisor.process.ConsumerProcessSupervisor.process(ConsumerProcessSupervisor.java:142) [hermes-consumers-0.11.3.jar:na]
        at pl.allegro.tech.hermes.consumers.supervisor.process.ConsumerProcessSupervisor.processSignal(ConsumerProcessSupervisor.java:119) [hermes-consumers-0.11.3.jar:na]
        at pl.allegro.tech.hermes.consumers.supervisor.process.ConsumerProcessSupervisor$$Lambda$143/859351810.accept(Unknown Source) [hermes-consumers-0.11.3.jar:na]
        at java.util.LinkedHashMap$LinkedKeySet.forEach(LinkedHashMap.java:555) [na:1.8.0_45]
        at java.util.Collections$SetFromMap.forEach(Collections.java:5476) [na:1.8.0_45]
        at pl.allegro.tech.hermes.consumers.supervisor.process.ConsumerProcessSupervisor.run(ConsumerProcessSupervisor.java:75) [hermes-consumers-0.11.3.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_45]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_45]
        a.lang.NullPointerExceptiont java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_45]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```
