### ISSUE TITLE
NullPointerException when creating a subscription without the topic name

### ISSUE THREAD

**Issue by SathyaBhat** [allegro/hermes#787]
As per the [documentation](http://hermes-pubsub.readthedocs.io/en/latest/user/subscribing/#creating-subscription), this request body 

```javascript
{
    "name": "mySubscription", 
    "endpoint": "http://my-service", 
    "owner": {
        "source": "Plaintext",
        "id": "My Team"
    }
}
```

is sufficient to create a subscription. However, this request body will result in a NullPointerException

```java
java.lang.NullPointerException: null
    at pl.allegro.tech.hermes.infrastructure.zookeeper.ZookeeperPaths.topicPath(ZookeeperPaths.java:66) ~[hermes-common-0.12.0.jar:na]
    at pl.allegro.tech.hermes.infrastructure.zookeeper.ZookeeperTopicRepository.ensureTopicExists(ZookeeperTopicRepository.java:43) ~[hermes-common-0.12.0.jar:na]
    at pl.allegro.tech.hermes.infrastructure.zookeeper.ZookeeperTopicRepository.getTopicDetails(ZookeeperTopicRepository.java:126) ~[hermes-common-0.12.0.jar:na]
    at pl.allegro.tech.hermes.infrastructure.zookeeper.ZookeeperTopicRepository.getTopicDetails(ZookeeperTopicRepository.java:117) ~[hermes-common-0.12.0.jar:na]
    at pl.allegro.tech.hermes.infrastructure.zookeeper.ZookeeperTopicRepository.isSubscribingRestricted(ZookeeperTopicRepository.java:122) ~[hermes-common-0.12.0.jar:na]
    at pl.allegro.tech.hermes.management.api.auth.ManagementRights.isUserAllowedToCreateSubscription(ManagementRights.java:31) ~[hermes-management-0.12.0.jar:na]
    at pl.allegro.tech.hermes.management.api.auth.ManagementRights$SubscriptionCreatorRights.allowedToCreate(ManagementRights.java:74) ~[hermes-management-0.12.0.jar:na]
    at pl.allegro.tech.hermes.management.domain.subscription.SubscriptionService.checkCreatorRights(SubscriptionService.java:82) ~[hermes-management-0.12.0.jar:na]
    at pl.allegro.tech.hermes.management.domain.subscription.SubscriptionService.createSubscription(SubscriptionService.java:75) ~[hermes-management-0.12.0.jar:na]
    at pl.allegro.tech.hermes.management.api.SubscriptionsEndpoint.create(SubscriptionsEndpoint.java:98) ~[hermes-management-0.12.0.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
    at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.23.2.jar:na]
    at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.23.2.jar:na]```
```

I was told in [chat](https://gitter.im/allegro/hermes?at=595baad94bcd78af56756650) that `topicName` should be part of the request body, and indeed if this is added, the request works fine (after adding `description` as well). 

So:

1. Need to put in validation so that the NPE is not thrown
2. Docs needs to be updated (I will send a PR for the docs update)

**Comment by adamdubiel** [comment]
Fixed in #791
