### ISSUE TITLE
Consumers unable to recover from Kafka problems

### ISSUE THREAD

**Issue by adamdubiel** [allegro/hermes#801]
If Kafka has issues, some consumer processes in Consumers have problems with recovering and throw exceptions like:

```
java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
	at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:1431)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:929)
	at pl.allegro.tech.hermes.consumers.consumer.receiver.kafka.KafkaSingleThreadedMessageReceiver.next(KafkaSingleThreadedMessageReceiver.java:88)
	at pl.allegro.tech.hermes.consumers.consumer.receiver.kafka.FilteringMessageReceiver.next(FilteringMessageReceiver.java:37)
	at pl.allegro.tech.hermes.consumers.consumer.SerialConsumer.consume(SerialConsumer.java:94)
	at pl.allegro.tech.hermes.consumers.supervisor.process.ConsumerProcess.run(ConsumerProcess.java:66)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by adamdubiel** [comment]
Fixed by #879
