### ISSUE TITLE
Problem updating max rate for consumer 

### ISSUE THREAD

**Issue by gamefundas** [allegro/hermes#825]
Noticed a strange exception in our consumer logs today. Not sure if this is a bug at this point but consumer fails to deliver the message and keeps retrying. 

Maxrate is not configured hence defaulted to 1.0 I guess and Hermes consumer version is 0.11.0

Stacktrace:
2017-10-03 07:00:18.043 WARN  p.a.t.h.c.c.r.m.MaxRateRegistry - Problem updating max rate for consumer ConsumerInstance{consumerId='my.host.ip.$8617448467065780411', subscription=x.x.x.x$mytopic.name}
com.fasterxml.jackson.databind.JsonMappingException: No suitable constructor found for type [simple type, class pl.allegro.tech.hermes.consumers.consumer.rate.maxrate.MaxRate]: can not instantiate from JSON object (missing default constructor or creator, or perhaps need to add/enable type information?)
at [Source: [B@53110e69; line: 1, column: 2]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1106)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2819)
        at pl.allegro.tech.hermes.consumers.consumer.rate.maxrate.MaxRateRegistry.updateMaxRateInCache(MaxRateRegistry.java:191)
        at pl.allegro.tech.hermes.consumers.consumer.rate.maxrate.MaxRateRegistry.lambda$handleContentUpdates$4(MaxRateRegistry.java:178)
        at pl.allegro.tech.hermes.infrastructure.zookeeper.cache.CacheListeners.call(CacheListeners.java:24)
        at pl.allegro.tech.hermes.infrastructure.zookeeper.cache.HierarchicalCacheLevel.childEvent(HierarchicalCacheLevel.java:68)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:522)
        at org.apache.curator.framework.recipes.cache.PathChildrenCache$5.apply(PathChildrenCache.java:516)
        at org.apache.curator.framework.listen.ListenerContainer$1.run(ListenerContainer.java:93)

**Comment by adamdubiel** [comment]
We noticed some strange behaviour with max-rate on consumers start, we are looking at it atm. CC: @dankraw

**Comment by gamefundas** [comment]
We recycled the node that was causing this problem and then things are fine. Its not clear if our cloudformation deployment pulled in a wrong version of consumer. Will report back if this thing shows up again.

**Comment by gamefundas** [comment]
This is still a problem. 

What I see is Jackson requires a default constructor or an annotation @JsonCreator that will help decide on the constructor to create MaxRate object during deserialization.

I am surprised this is not happening for you. Perhaps we are packaging a different version of Jackson that's sensitive about this. We have Jackson 2.6.5 bundled BTW. 

As a workaround we have suppressed the MaxrateRegistry logs as its literally floods the log files but was wondering what's the impact of this, the maxrate algorithm will not be able to kick in and consumer will default? Is it safe to use default?

Thanks
Andy

**Comment by dankraw** [comment]
Since hermes 1.2.2 we have a lightweight max-rate registry implementation, configured as `flat-binary` type: https://github.com/allegro/hermes/pull/1086
There's no jackson used at all, all contents are binary encoded using SBE. 

I'm closing the issue, as we consider the `hierarchical` max-rate registry as legacy. What's more we haven't observed this issue at all on our environments, it sound like a dependency version mismatch.
