### ISSUE TITLE
Abnormal delivery failure

### ISSUE THREAD

**Issue by gamefundas** [allegro/hermes#903]
We noticed the following WARN/ERROR in our logs few days back which couldn't be traced to any Kafka/Zk errors. The warnings (failed by kafka broker on topic) started for a series of messages around 16:00 EST and went on till 17:02 EST and then finally erroring out with "Abnormal delivery failure".

An example can be seen below in the logs, taken around the time when the warnings became errors. Looks like something retried for an hour before giving up. It not clear if consumer had trouble delivering the message to the subscriber endpoint. The subscriber and its endpoint seemed to be okay during this period. For little more than an hour this problem was seen and then everything was restored by itself. We lost about 20 messages during this period. 

Also to note during this time message delivery to other topics were as normal. I couldn't find anything that will lead me to the root cause especially that the reason is printed "null". 

Has this issue occurred to anyone before.

Logs:

```
2018-09-07 17:02:52.538 WARN  c.w.c.m.config.CustomLogRepository - [MYAPP] Message Id:e8365dd7-8042-4282-bdf4-2732d8d080c4 **failed by kafka broker on** topic:a.b.c.mytopic for subcription a.b.c.mysubscription and reason is :null

2018-09-07 17:02:52.540 WARN  p.a.t.h.c.c.r.DefaultErrorHandler - **Abnormal delivery failure**: subscription: a.b.c.mytopic$a.b.c.mysubscription; cause: null; endpoint: ; messageId: e8365dd7-8042-4282-bdf4-2732d8d080c4; partition: 0; offset: 863

2018-09-07 17:02:52.540 ERROR c.w.c.m.config.CustomLogRepository - [MYAPP] Message Id:e8365dd7-8042-4282-bdf4-2732d8d080c4 **failed by kafka broker on** topic:a.b.c.mytopic for subcription a.b.c.mysubscription reaon: **null**
```

Thanks
Andy

**Comment by druminski** [comment]
Hi,

I have found something similar in our production logs. However, our logback is configured to log also exceptions. Besides the 
```**Abnormal delivery failure**: subscription: a.b.c.mytopic$a.b.c.mysubscription; cause: null;```

I have found following stacktraces:

```
java.nio.channels.ClosedChannelException: null
        at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:498)
        at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:113)
        at org.eclipse.jetty.io.ChannelEndPoint.close(ChannelEndPoint.java:120)
        at org.eclipse.jetty.io.SelectChannelEndPoint.close(SelectChannelEndPoint.java:276)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:149)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:135)
        at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:121)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```
and 
```
java.nio.channels.AsynchronousCloseException: null
	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.close(HttpConnectionOverHTTP.java:135)

	at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:121)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

As far as I know this kind of exceptions are related to problems with connection to subscriber.

Probably further analyses is required on this subject but in the first place I recommend you enabling exception logging in logback.
